# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to learn and practice NumPy and Pandas

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [1]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [2]:
lst1 = [3, 6, 7, 8, 9]
arr1 = np.array(lst1)
print(type(lst1))
print(type(arr1))
print(arr1)

<class 'list'>
<class 'numpy.ndarray'>
[3 6 7 8 9]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [3]:
lst2 = [[3, 6, 7, 8, 9], [3, 6, 7, 8, 9], [3, 6, 7, 8, 9]]
arr2 = np.array(lst2)
print(arr2)

[[3 6 7 8 9]
 [3 6 7 8 9]
 [3 6 7 8 9]]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [4]:
lst3 = [[[3, 6, 7, 8, 9], [3, 6, 7, 8, 9], [3, 6, 7, 8, 9]], 
         [[3, 6, 7, 8, 9], [3, 6, 7, 8, 9], [3, 6, 7, 8, 9]], 
         [[3, 6, 7, 8, 9], [3, 6, 7, 8, 9], [3, 6, 7, 8, 9]]]
arr3 = np.array(lst3)
print(arr3)

[[[3 6 7 8 9]
  [3 6 7 8 9]
  [3 6 7 8 9]]

 [[3 6 7 8 9]
  [3 6 7 8 9]
  [3 6 7 8 9]]

 [[3 6 7 8 9]
  [3 6 7 8 9]
  [3 6 7 8 9]]]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [7]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)

In [4]:
20

20

In [11]:
#Code goes here

In [8]:
arr2 = np.tile(12, 7)
print(arr2)

arr3 = np.repeat([1, 2], 3)
print(arr3)

arr4 = np.arange(0, 100, 5, dtype="int")
print(arr4)

arr5 = np.linspace(0, 100, 5, dtype="int")
print(arr5)

arr6 = np.ones((3, 4, 4))
print(arr6)

arr7 = np.zeros((3, 4, 2))
print(arr7)

arr8 = np.random.rand(3, 4, 5)
print(arr8)

arr9 = np.random.randint(1, 200, 7)
print(arr9)

[12 12 12 12 12 12 12]
[1 1 1 2 2 2]
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[  0  25  50  75 100]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[0.69622492 0.07390848 0.73876786 0.90525386 0.43775241]
  [0.13701884 0.70750612 0.22012236 0.82348235 0.11856111]
  [0.49838342 0.56476424 0.219164   0.02702703 0.43263855]
  [0.98062269 0.7606584  0.86692933 0.8830813  0.09335415]]

 [[0.59870853 0.33318874 0.062572   0.40836666 0.95511992]
  [0.6007761  0.9140946  0.00107107 0.46891753 0.73909893]
  [0.8047061  0.9322074  0.3562004  0.52737253 0.00558505]
  [0.41928194 0.97603388 0.88937116 0.06890774 0.07597648]]

 [[0.90654406 0.53317032 0.94642088 0.41863069 0.37821087]
  [0.23617132 0.8145

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [9]:
arr1 = np.ones((3), dtype="int8")
print(arr1)
print(arr1.dtype)

arr1 = np.ones((3), dtype="int16")
print(arr1)
print(arr1.dtype)

arr1 = np.ones((3), dtype="float16")
print(arr1)
print(arr1.dtype)

arr1 = np.ones((3), dtype="bool_")
print(arr1)
print(arr1.dtype)

[1 1 1]
int8
[1 1 1]
int16
[1. 1. 1.]
float16
[ True  True  True]
bool


```python
array([ 6,  7,  8,  9, 10])
```

In [10]:
arr6 = np.ones((3, 4, 4))

print("Length of first dimension: " + str(len(arr6)))
print("Shape of array: " + str(arr6.shape))
print("Number of dimensions: " + str(arr6.ndim))
print("Size of array: " + str(arr6.size))
print("Data type of array: " + str(arr6.dtype))

Length of first dimension: 3
Shape of array: (3, 4, 4)
Number of dimensions: 3
Size of array: 48
Data type of array: float64


## 2.5 

Calculate the sum of all the numbers in `a`.

In [11]:
arr6b = arr6.reshape(4, 4, 3)
arr6c = arr6.reshape(4, 12)
arr6d = arr6.reshape(12, 4)
arr6e = arr6.reshape(48)
print(arr6b)
print(arr6c)
print(arr6d)
print(arr6e)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
arr10 = np.random.randint(1, 1200, 1000)
arr10b = arr10.reshape(-1, 10, 10)
arr10c = arr10.reshape(10, -1, 10)
arr10d = arr10.reshape(10, 10, -1)
print(arr10.shape)
print(arr10b.shape)
print(arr10c.shape)
print(arr10d.shape)

(1000,)
(10, 10, 10)
(10, 10, 10)
(10, 10, 10)


## 2.6 

Calculate the sum of each row in `a`.

In [10]:
# Code comes here

## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [12]:
# Code comes here

# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [13]:
# Codes comes here

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [14]:
# Code comes here

## 2.10 

How many rows and columns are there in the dataframe?

In [15]:
#Code comes here

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [16]:
# Code comes here

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [17]:
# Code comes here

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [18]:
#code comes here

## 2.14

Which country consumes the least amount of beef per person per year?


In [19]:
# code comes here

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [20]:
# code comes here

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [21]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assitance.